/* Content layer: update catalog, domains, and question records here—not in the UI. */
const certifications = [
 {id:'ai-business-strategist',code:'AIB-C01',name:'AWS Certified AI Business Strategist',shortName:'AI Business Strategist',level:'Business',description:'Validate business judgment for evaluating, governing, and scaling AI adoption.',officialUrl:'https://aws.amazon.com/certification/certified-ai-business-strategist/',exam:{durationMinutes:170,officialQuestionCount:85,format:'Multiple choice / multiple response'},domains:['AI Fundamentals and Literacy','AI Strategy and Business Value Creation','AI Governance and Responsible AI Leadership','Business Readiness, Leadership, and AI Transformation'],practice:{mockQuestionCount:40}},
 {id:'cloud-practitioner',code:'CLF-C02',name:'AWS Certified Cloud Practitioner',shortName:'Cloud Practitioner',level:'Foundational',description:'Validate foundational cloud, AWS services, and cloud-computing knowledge.',officialUrl:'https://aws.amazon.com/certification/certified-cloud-practitioner/',exam:{durationMinutes:90,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Cloud concepts','Security and compliance','Cloud technology and services','Billing and pricing'],practice:{mockQuestionCount:40}},
 {id:'ai-practitioner',code:'AIF-C01',name:'AWS Certified AI Practitioner',shortName:'AI Practitioner',level:'Foundational',description:'Validate foundational artificial intelligence, machine learning, generative AI, and AWS AI service knowledge.',officialUrl:'https://aws.amazon.com/certification/certified-ai-practitioner/',exam:{durationMinutes:90,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['AI and ML fundamentals','Generative AI fundamentals','Foundation models','Responsible AI'],practice:{mockQuestionCount:40}},
 {id:'solutions-architect-associate',code:'SAA-C03',name:'AWS Certified Solutions Architect – Associate',shortName:'Solutions Architect – Associate',level:'Associate',description:'Design practical, secure, resilient AWS architectures.',officialUrl:'https://aws.amazon.com/certification/certified-solutions-architect-associate/',exam:{durationMinutes:130,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Secure Architectures','Resilient Architectures','High-Performing Architectures','Cost-Optimized Architectures'],practice:{mockQuestionCount:40},domainDistribution:[{domain:'Secure Architectures',weight:.25},{domain:'Resilient Architectures',weight:.25},{domain:'High-Performing Architectures',weight:.25},{domain:'Cost-Optimized Architectures',weight:.25}]},
 {id:'developer-associate',code:'DVA-C02',name:'AWS Certified Developer – Associate',shortName:'Developer – Associate',level:'Associate',description:'Develop, test, deploy, and debug AWS Cloud applications.',officialUrl:'https://aws.amazon.com/certification/certified-developer-associate/',exam:{durationMinutes:130,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Development with AWS services','Security','Deployment','Troubleshooting'],practice:{mockQuestionCount:40}},
 {id:'cloudops-associate',code:'SOA-C02',name:'AWS Certified CloudOps Engineer – Associate',shortName:'CloudOps Engineer – Associate',level:'Associate',description:'Deploy, manage, and operate workloads on AWS.',officialUrl:'https://aws.amazon.com/certification/certified-cloudops-engineer-associate/',exam:{durationMinutes:130,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Monitoring','Reliability','Security','Networking','Cost optimization'],practice:{mockQuestionCount:40}},
 {id:'data-engineer-associate',code:'DEA-C01',name:'AWS Certified Data Engineer – Associate',shortName:'Data Engineer – Associate',level:'Associate',description:'Design data models, manage data lifecycles, and ensure data quality on AWS.',officialUrl:'https://aws.amazon.com/certification/certified-data-engineer-associate/',exam:{durationMinutes:130,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Data ingestion','Data transformation','Data operations','Data security and governance'],practice:{mockQuestionCount:40}},
 {id:'machine-learning-engineer-associate',code:'MLA-C01',name:'AWS Certified Machine Learning Engineer – Associate',shortName:'Machine Learning Engineer – Associate',level:'Associate',description:'Implement and operationalize machine-learning workloads in production.',officialUrl:'https://aws.amazon.com/certification/certified-machine-learning-engineer-associate/',exam:{durationMinutes:130,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Data preparation','Model development','Deployment','Monitoring'],practice:{mockQuestionCount:40}},
 {id:'solutions-architect-professional',code:'SAP-C02',name:'AWS Certified Solutions Architect – Professional',shortName:'Solutions Architect – Professional',level:'Professional',description:'Design solutions for complex organizational and technical requirements.',officialUrl:'https://aws.amazon.com/certification/certified-solutions-architect-professional/',exam:{durationMinutes:180,officialQuestionCount:75,format:'Multiple choice / multiple response'},domains:['Organizational complexity','New solutions','Continuous improvement','Migration'],practice:{mockQuestionCount:40}},
 {id:'devops-professional',code:'DOP-C02',name:'AWS Certified DevOps Engineer – Professional',shortName:'DevOps Engineer – Professional',level:'Professional',description:'Automate, operate, secure, and improve resilient delivery systems.',officialUrl:'https://aws.amazon.com/certification/certified-devops-engineer-professional/',exam:{durationMinutes:180,officialQuestionCount:75,format:'Multiple choice / multiple response'},domains:['SDLC automation','Configuration management','Resilient cloud solutions','Monitoring and logging'],practice:{mockQuestionCount:40}},
 {id:'generative-ai-developer-professional',code:'AIG-C01',name:'AWS Certified Generative AI Developer – Professional',shortName:'Generative AI Developer – Professional',level:'Professional',description:'Build production-grade generative-AI solutions on AWS.',officialUrl:'https://aws.amazon.com/certification/certified-generative-ai-developer-professional/',exam:{durationMinutes:null,officialQuestionCount:null,format:'See official AWS certification page'},domains:['Generative AI applications','Foundation models','Security','Operations'],practice:{mockQuestionCount:40}},
 {id:'advanced-networking-specialty',code:'ANS-C01',name:'AWS Certified Advanced Networking – Specialty',shortName:'Advanced Networking – Specialty',level:'Specialty',description:'Handle critical and complex networking on AWS.',officialUrl:'https://aws.amazon.com/certification/certified-advanced-networking-specialty/',exam:{durationMinutes:170,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Network design','Network implementation','Network management','Security'],practice:{mockQuestionCount:40}},
 {id:'security-specialty',code:'SCS-C02',name:'AWS Certified Security – Specialty',shortName:'Security – Specialty',level:'Specialty',description:'Secure AWS workloads, architectures, and data.',officialUrl:'https://aws.amazon.com/certification/certified-security-specialty/',exam:{durationMinutes:170,officialQuestionCount:65,format:'Multiple choice / multiple response'},domains:['Threat detection','Security logging','Infrastructure security','Data protection'],practice:{mockQuestionCount:40}}
];
const saaQuestionTemplates = [
 ['Secure Architectures','medium','A company needs to give an application running on Amazon EC2 read-only access to one S3 bucket. Which approach is the most secure?',['Attach an IAM role with only s3:GetObject permission for the required bucket to the EC2 instance.','Store an IAM user access key in the application configuration file.','Make the bucket public and restrict access by object name.','Use the root user access keys in an environment variable.'],0,'An IAM role provides short-lived credentials without embedding secrets. Least-privilege bucket access limits the application to the required action and resource.'],
 ['Secure Architectures','easy','A security team needs to detect if an S3 bucket becomes publicly accessible. Which AWS service provides this managed check?',['AWS Config with a managed rule and notifications.','Amazon CloudFront access logs only.','Amazon EC2 Auto Scaling.','AWS Snowball Edge.'],0,'AWS Config evaluates resource configurations over time. Managed rules can identify public S3 buckets and trigger remediation workflows.'],
 ['Resilient Architectures','medium','A web application must remain available if one Availability Zone fails. Which design best meets this requirement?',['Run instances in an Auto Scaling group across multiple Availability Zones behind an Application Load Balancer.','Run one large instance with a larger EBS volume.','Place all instances in one Availability Zone with frequent snapshots.','Use a single NAT gateway for all workloads.'],0,'Multi-AZ Auto Scaling with an Application Load Balancer removes dependence on a single Availability Zone and replaces unhealthy capacity.'],
 ['Resilient Architectures','hard','An application writes orders to a database and must continue accepting requests during a regional service disruption. Which pattern is most appropriate?',['Use DynamoDB global tables with application routing designed for multiple Regions.','Use one Multi-AZ RDS instance and wait for it to recover.','Store the orders on an EC2 instance store volume.','Use an S3 lifecycle rule to copy backups weekly.'],0,'DynamoDB global tables replicate data across selected Regions and support multi-Region application designs. Multi-AZ protects within a Region, not against a regional event.'],
 ['High-Performing Architectures','medium','Users upload large files directly to a web application. The application servers are becoming a bottleneck. What should the architect recommend?',['Generate S3 presigned URLs so clients upload directly to Amazon S3.','Increase the web server instance size.','Send files through a NAT gateway before storing them.','Save all files in an Amazon EFS file system.'],0,'Presigned URLs let clients upload directly to S3 while retaining controlled, time-limited access. This removes file transfer work from the application tier.'],
 ['High-Performing Architectures','medium','A globally distributed audience experiences high latency when loading static assets from an S3 bucket. Which solution improves delivery performance?',['Use Amazon CloudFront with the S3 bucket as an origin.','Move the bucket to a larger EC2 instance.','Use an EBS volume attached to the web servers.','Send every request through AWS Site-to-Site VPN.'],0,'CloudFront caches static objects at edge locations close to viewers, reducing latency and origin load.'],
 ['Cost-Optimized Architectures','easy','A development environment is used only during business hours and has predictable usage. Which option most directly reduces compute cost?',['Schedule nonproduction EC2 instances to stop outside required hours.','Use larger On-Demand instances at all times.','Store application logs only in instance memory.','Move the workload to a single Availability Zone.'],0,'Stopping nonproduction instances when they are not needed avoids compute charges while retaining the ability to restart them.'],
 ['Cost-Optimized Architectures','medium','A company retains data for several years. Data is accessed frequently for 30 days and rarely afterward, but must be retrievable when required. Which S3 approach is appropriate?',['Use an S3 Lifecycle rule to transition objects to a lower-cost storage class after 30 days.','Delete all objects after 30 days.','Keep all objects in S3 Standard indefinitely.','Copy objects manually to an EC2 instance.'],0,'Lifecycle policies automate transitions based on age and access requirements, reducing storage cost while preserving retrieval.'],
 ['Secure Architectures','hard','A company must encrypt data in S3 and control key usage through its own key policy. Which option is appropriate?',['Use SSE-KMS with a customer managed AWS KMS key.','Use SSE-S3 and share the bucket password.','Use an unencrypted EBS volume.','Use CloudFront signed cookies for encryption at rest.'],0,'SSE-KMS with a customer managed key provides encryption at rest plus key policies, grants, and auditability through AWS KMS.'],
 ['Resilient Architectures','easy','A workload uses an Amazon RDS database and requires automatic failover within a Region. Which configuration should be selected?',['Amazon RDS Multi-AZ deployment.','A single RDS instance with manual snapshots.','An EC2-hosted database on one instance.','An Amazon S3 static website.'],0,'RDS Multi-AZ maintains a standby in another Availability Zone and performs managed failover for supported engine deployments.'],
 ['High-Performing Architectures','hard','An API receives unpredictable traffic bursts and tasks can be processed asynchronously. Which architecture scales efficiently?',['Amazon API Gateway, Amazon SQS, and AWS Lambda consumers.','A fixed fleet of one EC2 instance.','A manual file transfer process.','A single EBS volume shared over the internet.'],0,'API Gateway accepts requests, SQS buffers bursts, and Lambda scales consumers based on queued work. This decouples ingestion from processing.'],
 ['Cost-Optimized Architectures','hard','A batch workload is fault tolerant and can pause when capacity is unavailable. Which purchasing option is generally suited to this workload?',['Amazon EC2 Spot Instances.','Dedicated Hosts only.','A permanently running On-Demand instance.','Provisioned IOPS for an unused volume.'],0,'Spot Instances can offer significant savings for interruption-tolerant workloads. Applications should checkpoint and handle interruptions.']
];
function createQuestionBank(){const bank=[]; saaQuestionTemplates.forEach((t,templateIndex)=>{for(let v=1;v<=5;v++){const [domain,difficulty,question,options,correctAnswer,explanation]=t;bank.push({id:`SAA-${String(templateIndex*5+v).padStart(3,'0')}`,certification:'solutions-architect-associate',domain,difficulty,type:'single-answer',question:v===1?question:question.replace('A company','An organization'),options:[...options],correctAnswer,explanation,referenceLinks:[{title:'AWS Documentation',url:'https://docs.aws.amazon.com/'}]})}});return bank}
const questionBank=createQuestionBank();
