const fs = require('fs'); const assert = require('assert');
const sql = fs.readFileSync('supabase/migrations/001_certification_practice.sql','utf8');
for (const table of ['profiles','certifications','certification_domains','questions','question_options','question_answers','exam_attempts','exam_attempt_questions','exam_answers','user_question_history','saved_questions','practice_domain_attempts','audit_events']) assert(sql.includes(`public.${table}`), `${table} is missing`);
for (const fn of ['create_exam','save_exam_answer','submit_exam','get_exam_review','my_dashboard']) assert(sql.includes(`function public.${fn}`), `${fn} is missing`);
assert(sql.includes('enable row level security'), 'RLS must be enabled');
assert(sql.includes('auth.uid()'), 'ownership must be session-based');
assert(!/grant select on public\.question_answers to anon/i.test(sql), 'answer keys must not be public');
assert(sql.includes('keeps_current_role'), 'normal users must not self-promote via profile updates');
assert(/reference_links jsonb not null/i.test(sql), 'question reference_links must use a safe identifier');
assert(!/\breferences\s+jsonb/i.test(sql), 'reserved references must not be used as a column name');
assert(/^begin;[\s\S]*commit;\s*$/im.test(sql), 'initial migration must be transactional');
const questions = JSON.parse(fs.readFileSync('supabase/existing-questions.seed.json', 'utf8'));
assert(questions.every(question => question.certification === 'solutions-architect-associate'), 'existing SAA questions must use the canonical SAA slug');
assert(questions.every(question => Array.isArray(question.reference_links)), 'question seed must use reference_links');
const evolution = fs.readFileSync('supabase/migrations/003_exam_versions_content_readiness.sql', 'utf8');
for (const required of ['certification_exam_versions', 'publication_status', 'exam_version_id', 'minimum_practice_available', "publication_status='published'"]) assert(evolution.includes(required), `missing schema evolution: ${required}`);
const statusFix = fs.readFileSync('supabase/migrations/004_fix_exam_attempt_status_enum.sql', 'utf8');
for (const required of ["'in_progress'::public.attempt_status", "'submitted'::public.attempt_status", "'expired'::public.attempt_status", 'function public.submit_exam', 'for update']) assert(statusFix.includes(required), `missing enum-safe submission contract: ${required}`);
assert(!/set\s+status\s*=\s*case[\s\S]*then\s+'expired'(?!::public\.attempt_status)[\s\S]*else\s+'submitted'(?!::public\.attempt_status)/i.test(statusFix), 'submission status CASE must use attempt_status values');
const selection = fs.readFileSync('supabase/migrations/005_question_selection_and_versioning.sql', 'utf8');
for (const required of ['exam_version_id', 'domain_weight_snapshot', 'recency_rank <= 40', 'publication_status = \'published\'', 'function public.create_exam']) assert(selection.includes(required), `missing version-aware repeat-avoidance contract: ${required}`);
assert(!/grant execute on function public\.create_exam[^;]+to anon/i.test(selection), 'exam creation must remain authenticated-only');
console.log('Backend contract checks passed.');
